In [1]:
import numpy as np

In [2]:
#assign input values
input_value = np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [3]:
#assign output values
output=np.array([0,1,1,0])
output=output.reshape(4,1)
output.shape

(4, 1)

In [4]:
#assign weights
weigths=np.array([[0.1],[0.2]])
weigths

array([[0.1],
       [0.2]])

In [5]:
#assign bias
bias=0.3

In [6]:
#Activation function
def sigmoid_func(x):
    return 1/(1 + np.exp(-x))

In [7]:
#Derivative of Sigmoid function
def der(x):
    return sigmoid_func(x) * (1- sigmoid_func(x))

In [8]:
#Updating weigths
for epochs in range(10000):
    input_arr = input_value
    
    weighted_sum=np.dot(input_arr, weigths) + bias
    first_output=sigmoid_func(weighted_sum)
    
    error =first_output - output
    total_error=np.square(np.subtract(first_output,output)).mean()
    
    first_der = error
    second_der = der(first_output)
    derivative = first_der * second_der
    
    t_input = input_value.T
    final_derivative = np.dot(t_input, derivative)
    
    #update weights
    weigths = weigths - 0.05 * final_derivative
    
    #update bias
    for i in derivative:
        bias = bias - 0.05 * i

In [9]:
print(weigths)

[[-0.41953547]
 [ 8.98887811]]


In [10]:
print(bias)

[-4.19706344]


In [11]:
pred = np.array([0,1])
result = np.dot(pred, weigths) + bias

res = sigmoid_func(result)

print(res)

[0.99177089]
